param(
    [string]$Distro = "Ubuntu",
    [string]$WslRepoPath = "",
    [string]$WindowsConfigPath = "$env:USERPROFILE\.wezterm.lua"
)

$ErrorActionPreference = "Stop"

if (-not (Get-Command wsl.exe -ErrorAction SilentlyContinue)) {
    throw "wsl.exe was not found. Install WSL and Ubuntu first."
}

if (-not (Get-Command claude -ErrorAction SilentlyContinue)) {
    Invoke-RestMethod https://claude.ai/install.ps1 | Invoke-Expression
}

if ([string]::IsNullOrWhiteSpace($WslRepoPath)) {
    $WslRepoPath = (wsl.exe -d $Distro --cd "~" --exec zsh -lc 'printf "%s" "${DOTFILES_DIR:-$HOME/dotfiles}"')
}

$WslRepoPath = $WslRepoPath.Trim()
$wslUser = (wsl.exe -d $Distro --exec sh -lc 'printf "%s" "$USER"').Trim()

wsl.exe -d $Distro --exec sh -lc @'
if command -v apt-get >/dev/null 2>&1; then
    sudo apt-get update
    sudo apt-get install -y bubblewrap xclip
elif command -v dnf >/dev/null 2>&1; then
    sudo dnf install -y bubblewrap xclip
elif command -v pacman >/dev/null 2>&1; then
    sudo pacman -Sy --needed bubblewrap xclip
else
    echo "skip: install bubblewrap manually inside WSL; unsupported package manager" >&2
fi
'@

$uncRepoPath = "\\wsl.localhost\$Distro$($WslRepoPath -replace '/', '\')"
$weztermConfig = Join-Path $uncRepoPath "home\.config\wezterm\wezterm.lua"

$shim = @"
-- Generated by dotfiles/scripts/windows.ps1.
-- Keep the real configuration in WSL dotfiles.
dofile([[$weztermConfig]])
"@

Set-Content -Path $WindowsConfigPath -Value $shim -Encoding UTF8

Write-Host "linked: $WindowsConfigPath -> $weztermConfig"
Write-Host "WSL distro: $Distro"
Write-Host "WSL user:   $wslUser"
